---
title: "arkansas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mapview)
library(rgdal)
library(sf)
library(ggplot2)
library(stringr)
```

## Network Graphs
```{r}
#loading the package:
library(igraph)

#Read the network data:
net <- read.csv("./coopmaps/arkansas/data/aecc-edges.csv")

#Read the node attribute data
node_attrib <- read.csv("./coopmaps/arkansas/data/aecc-geocoded-nodes.csv")

#we will convert the id to a character for later manipulation:
node_attrib$idch <- as.character(node_attrib$ID)
```

```{r}
g1 <- graph.data.frame(net, directed = T)
#we can print a summary of the network to see tha attributes and number of edges and nodes:
#summary(g1)

poss <- match(V(g1)$name,node_attrib$idch)
V(g1)$lat <- node_attrib$lat[poss]
V(g1)$long <- node_attrib$lng[poss]
V(g1)$type <- as.character(node_attrib$Label[poss])
V(g1)$fullname <- as.character(node_attrib$Name[poss])
V(g1)$address <- as.character(node_attrib$formatted_address[poss])

#if we ask for the summary again we can see the added attributes:
#summary(g1)
```
```{r}
## The centrality measures can be helpful to describe the network and find nodes that could be interesting.  Here we compute some centrality measures and we add it to the network:
#centrality measures for the full network (no loops)

indeg <- degree(g1, v=V(g1), mode=c("in"),loops=FALSE)
outdeg <- degree(g1, v=V(g1), mode=c("out"),loops=FALSE)

indegN <- degree(g1, v=V(g1), mode=c("in"),loops=FALSE, normalized=TRUE)
outdegN <- degree(g1, v=V(g1), mode=c("out"),loops=FALSE,normalized=TRUE)

inclose <- closeness(g1, v=V(g1), mode = ("in"))
outclose <- closeness(g1, v=V(g1), mode = ("out"))
bet <- betweenness(g1, v=V(g1), directed = TRUE)
betN <- bet/max(bet)

## add centrality measures to node attributes
V(g1)$indeg <- indeg
V(g1)$outdeg <- outdeg
V(g1)$indegN <- indegN
V(g1)$outdegN <- outdegN
V(g1)$inclose <- inclose
V(g1)$outclose <- outclose
V(g1)$bet <- bet
V(g1)$betN <- betN

```
```{r eval=FALSE, include=TRUE}
plot(g1, layout = layout_components, vertex.label = NA, vertex.size = 5, edge.arrow.size = .4)
```


# The Whole Network
```{r}
par(mfrow=c(1,1),mar=c(0,3,1,0))
colpal <- c("red", "blue", "yellow", "green", "orange")
plot(g1, layout = layout_components, vertex.size = 11, edge.arrow.size = .4, 
     vertex.color = rainbow(12)[factor(V(g1)$type)],
     main = "Arkansas Electric Cooperative Network")
legend("bottomleft", legend = levels(factor(V(g1)$type)), col = rainbow(12),
       pch = 16, bty = "n", title = "Node Type", inset=c(-0.1,0))

```

