---
title: "Create centralized node table"
author: "Tyler Jackson"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libs

```{r}
library(dplyr)
library(mapview)
library(rgdal)
library(sf)
library(ggplot2)
library(stringr)
library(scales)
#loading the package:
library(igraph)
library(ggmap)
library(maps)
library(ggthemes)
library(mapdata)
library(tidyverse)
library(ggrepel)
library(networkD3)
```


# data

```{r}
nodes_sc <- read.csv("sc_nodes.csv", stringsAsFactors = F)

nodes_in <- read.csv("in_nodes-geocoded.csv", stringsAsFactors = F)

nodes_in <- rename(nodes_in, Label = label)



edges_sc <- read.csv("sc_egdes.csv", stringsAsFactors = F)

edges_sc <- edges_sc %>%
  select(Source, Target)
# note same df lol.
edges_in <- read.csv("in_edges.csv", stringsAsFactors = F)

names(edges_in) <- c("Source", "Target")

```

# create lookup table

```{r}
lookup_table <- nodes_sc %>%
  full_join(nodes_in, by="Label") %>%
  rename(sc_id=ID.x, in_id=ID.y) %>%
  mutate(natl_id=1:n()) %>%
  select(sc_id, natl_id, in_id)
lookup_table
```

# renaming ids

```{r}
new_edges_sc <- edges_sc %>%
  left_join(lookup_table, by=c("Source"="sc_id")) %>%
  select(-in_id, -Source) %>%
  rename(Source=natl_id) %>%
  left_join(lookup_table, by=c("Target"="sc_id")) %>%
  select(-in_id, -Target) %>%
  rename(Target=natl_id)

new_edges_sc
```

```{r}
new_edges_indi <- edges_in %>%
  left_join(lookup_table, by=c("Source"="in_id")) %>%
  select(-sc_id, -Source) %>%
  rename(Source=natl_id) %>%
  left_join(lookup_table, by=c("Target"="in_id")) %>%
  select(-sc_id, -Target) %>%
  rename(Target=natl_id)

new_edges_indi

natl_edges <- rbind(new_edges_indi, new_edges_sc)
```

Create nodes table
```{r}
natl_nodes <- nodes_sc %>%
  full_join(nodes_in, by="Label") %>%
  rename(sc_id=ID.x, in_id=ID.y) %>%
  mutate(natl_id = 1:n(), 
         State=coalesce(State.x, State.y), 
         cat1=coalesce(cat1.x, cat1.y),
         cat2=coalesce(cat2.x, cat2.y),
         cat3=coalesce(cat3.x, cat3.y),
         zipcode = coalesce(Zip, zip),
         url = coalesce(url.x, url.y),
         Notes = coalesce(Notes, notes),
         address = coalesce(formatted_address.x, formatted_address.y),
         lon = coalesce(lng.x, lng.y),
         lat = coalesce(lat.x, lat.y)) %>%
  select(natl_id, Label, address, State, zipcode, cat1, cat2, 
         cat3, url, Notes, lon, lat)
     
natl_nodes$cat2 <- 
  str_replace(natl_nodes$cat2, "Associations", "Association")

write.csv(natl_nodes, file = "natl_nodes.csv")

write.csv(natl_edges, file = "natl_edges.csv")

```

```{r}
coops <- natl_nodes

coops.sf <- st_as_sf(x = coops[!is.na(coops$lat),], 
                        coords = c("lon", "lat"),
                        crs = "+proj=longlat +datum=WGS84")
```

```{r echo=FALSE}
mapview(coops.sf, zcol = "cat2", legend = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

#Read the network data:
net <- natl_edges
#Read the node attribute data
node_attrib <- coops
#we will convert the id to a character for later manipulation:
node_attrib$idch <- as.character(node_attrib$natl_id)
```

```{r echo=FALSE}
g1 <- graph.data.frame(net, directed = F)
#we can print a summary of the network to see tha attributes and number of edges and nodes:
#summary(g1)

poss <- match(V(g1)$name,node_attrib$idch)
V(g1)$lat <- node_attrib$lat[poss]
V(g1)$long <- node_attrib$lon[poss]
V(g1)$cat1 <- as.character(node_attrib$cat1[poss])
V(g1)$cat2 <- as.character(node_attrib$cat2[poss])
V(g1)$cat3 <- as.character(node_attrib$cat3[poss])
V(g1)$fullname <- as.character(node_attrib$Label[poss])
V(g1)$state <- as.character(node_attrib$State[poss])
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#The centrality measures can be helpful to describe the network and find nodes that could be interesting.  Here we compute some centrality measures and we add it to the network:
#centrality measures for the full network (no loops)
indeg <- degree(g1, v=V(g1), mode=c("in"),loops=FALSE)
outdeg <- degree(g1, v=V(g1), mode=c("out"),loops=FALSE)
alldeg <- degree(g1, v=V(g1), mode=c("all"),loops=FALSE)
indegN <- degree(g1, v=V(g1), mode=c("in"),loops=FALSE, normalized=TRUE)
outdegN <- degree(g1, v=V(g1), mode=c("out"),loops=FALSE,normalized=TRUE)

inclose <- closeness(g1, v=V(g1), mode = ("in"))
outclose <- closeness(g1, v=V(g1), mode = ("out"))
bet <- betweenness(g1, v=V(g1), directed = TRUE)
betN <- bet/max(bet)

## add centrality measures to node attributes
V(g1)$indeg <- indeg
V(g1)$outdeg <- outdeg
V(g1)$indegN <- indegN
V(g1)$outdegN <- outdegN
V(g1)$inclose <- inclose
V(g1)$outclose <- outclose
V(g1)$bet <- bet
V(g1)$betN <- betN
V(g1)$alldeg <- alldeg
```

```{r eval=FALSE, include=FALSE}
plot(g1, layout = layout_components, vertex.label = NA, vertex.size = alldeg, edge.arrow.size = .4)
```

```{r}
tiff("natl.tiff", units="in", width=6, height=5, res=300)
par(mfrow=c(1,1),mar=c(0,3,1,0))
plot(g1, layout = layout_components, vertex.size = 11, 
     edge.arrow.size = .4, 
     vertex.color = rainbow(7)[factor(V(g1)$cat2)],
     main = "Indiana & South Carolina Electric Cooperative Network")
legend("bottomleft", legend = levels(factor(V(g1)$cat2)), 
       col = rainbow(7),
       pch = 16, bty = "n", title = "Node Type", inset=c(-0.1,0))
dev.off()
```

