---
title: "lookup_table_sample"
author: "Kenji Tomari"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libs

```{r}
library(dplyr)
```


# data

```{r}
nodes_sc <- data.frame(
  ID = 1:4,
  Label = LETTERS[1:4],
  stringsAsFactors = F
)

nodes_indi <- data.frame(
  ID = 1:4,
  Label = LETTERS[4:7],
  stringsAsFactors = F
)

edges_sc <- data.frame(
  Source = c(1,1,3,4),
  Target = c(2,4,3,2)
)

# note same df lol.
edges_indi <- data.frame(
  Source = c(1,1,3,4),
  Target = c(2,4,3,2)
)


```

# create lookup table

```{r}
lookup_table <- nodes_sc %>%
  full_join(nodes_indi, by="Label") %>%
  rename(sc_id=ID.x, indi_id=ID.y) %>%
  mutate(natl_id=1:n()) %>%
  select(-Label)
lookup_table
```

# renaming ids

```{r}
new_edges_sc <- edges_sc %>%
  left_join(lookup_table, by=c("Source"="sc_id")) %>%
  select(-indi_id, -Source) %>%
  rename(Source=natl_id) %>%
  left_join(lookup_table, by=c("Target"="sc_id")) %>%
  select(-indi_id, -Target) %>%
  rename(Target=natl_id)

new_edges_sc
```

```{r}
new_edges_indi <- edges_indi %>%
  left_join(lookup_table, by=c("Source"="indi_id")) %>%
  select(-sc_id, -Source) %>%
  rename(Source=natl_id) %>%
  left_join(lookup_table, by=c("Target"="indi_id")) %>%
  select(-sc_id, -Target) %>%
  rename(Target=natl_id)

new_edges_indi
```

