---
title: "lookup example"
author: "Tyler Jackson"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# dummy data

```{r}
indi_nodes <- data.frame(
  ID = c(6:9),
  label = c( "Lol", "AK Energy", "woot", "puppies"),
  stringsAsFactors = F
)

sc_nodes <- data.frame(
  ID = c(1:4),
  label = c("AK Energy", "haha", "super cool", "wow!"),
  stringsAsFactors = F
)

sc_edges <- data.frame(
  Source = c(1, 1, 3, 4),
  Target = c(3, 4, 2, 2)
)

lookup_table <- data.frame(
  indi_id = c(6, NA, NA, NA, 7:9),
  sc_id = c(1:4, NA, NA, NA),
  natl_id = c(10:16)
)
```

# compare ids

```{r}
# pick a base list, in this case south carolina
matches_in_indi <- which(indi_nodes$label %in% sc_nodes$label)
unmatched_indi <- indi_nodes[!matches_in_indi,]
matched_indi <- indi_nodes[matches_in_indi,]

# repeat for sc


# now build look up table

# remove label column, replace it with sc_id or indi_id; also rename ID to sc_id or indi_id as needed; then fill in new column with NAs, then rbind those fuckers
```


```{r}
#' Renames column based on lookup table
#'
#' @param df is your data.frame to change (edges list)
#' @param lookup is your look up data.frame
#' @param x is the region column
renamer <- function(df, lookup, x) {
  # get sources
  df$Source <- sapply(df$Source, function(y){
    lookup[which(lookup[x] == y), "natl_id"]
  })
  
  df$Target <- sapply(df$Target, function(y){
    lookup[which(lookup[x] == y), "natl_id"]
  })
  
  # return
  df
}
```

```{r}
renamer(df=sc_edges, lookup=lookup_table, x="sc_id")
```


